# config/packages/knp_paginator.yaml
knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: 'pagination/tailwind_pagination.html.twig'  # Notez le changement ici